import Matter from 'matter-js';
import { getRecipePhysicsProfile } from '../data/recipePhysicsProfiles';

export type PhysicsPoint={x:number;y:number};
export type RecipePhysicsLayer='front'|'middle'|'back'|'accent';
export type RecipeLayoutBehavior='natural'|'clumps'|'even'|'stacked'|'spread';
export type RecipePlacementMode='scatter'|'stack'|'front-fill'|'back-attract';
export type RecipeDropOrder='random'|'grouped';
export type OpenSpaceFill='off'|'light'|'medium'|'strong';
export type PlantSpacing='tight'|'natural'|'loose';
export type PlantGrouping='individual'|'small-drift'|'medium-drift'|'large-drift'|'continuous-mass';
export type GroupGap='small'|'medium'|'large';

export interface RecipePhysicsPlant{key:string;plantId:number;radius:number;layer:RecipePhysicsLayer;weight:number;clump?:number;count?:number;enabled?:boolean;frontAttraction?:number;backAttraction?:number;edgeAttraction?:number;repetition?:string;mode?:RecipePlacementMode;spacing?:PlantSpacing;grouping?:PlantGrouping;groupGap?:GroupGap;}
export interface RecipePhysicsOptions{polygon:PhysicsPoint[];plants:RecipePhysicsPlant[];seed:number;density?:number;targetCount?:number;frontEdges?:number[];backEdges?:number[];iterations?:number;passes?:number;padding?:number;allowedOverlap?:number;attractionStrength?:number;clumpStrength?:number;layoutBehavior?:RecipeLayoutBehavior;keepCentersInside?:boolean;dropOrder?:RecipeDropOrder;physicsScale?:number;spacingPad?:number;openSpaceFill?:OpenSpaceFill;}
export interface RecipePhysicsPlacement{key:string;plantId:number;layer:RecipePhysicsLayer;x:number;y:number;radius:number;rotationDeg:number;driftId?:string;}
export interface RecipePhysicsCycle{cycle:number;requested:number;placed:number;coverage:number;pruned:number;refilled:number;}
export interface RecipePhysicsResult{placements:RecipePhysicsPlacement[];diagnostics:{requested:number;placed:number;rejected:number;unresolvedOverlaps:number;seed:number;capacity:number;capacityLimited:boolean;estimatedCoverage:number;passes:number;targetCoverage:number;cycles:RecipePhysicsCycle[];driftCenters:Array<{id:string;plantId:number;x:number;y:number;grouping:PlantGrouping;gapDiameters:number}>;};}

type ExpandedPlant=RecipePhysicsPlant&{ordinal:number;driftId?:string;driftCenter?:PhysicsPoint};
type RecordBody={body:Matter.Body;plant:ExpandedPlant;target:PhysicsPoint;rotationDeg:number};

const clamp=(v:number,min=0,max=1)=>Math.max(min,Math.min(max,v));
function rng(seed:number){let v=seed>>>0;return()=>{v+=0x6d2b79f5;let t=v;t=Math.imul(t^(t>>>15),t|1);t^=t+Math.imul(t^(t>>>7),t|61);return((t^(t>>>14))>>>0)/4294967296;};}
function shuffle<T>(items:T[],random:()=>number){const out=[...items];for(let i=out.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[out[i],out[j]]=[out[j],out[i]];}return out;}
export function pointInPolygon(p:PhysicsPoint,poly:PhysicsPoint[]){let hit=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const a=poly[i],b=poly[j];if((a.y>p.y)!==(b.y>p.y)&&p.x<((b.x-a.x)*(p.y-a.y))/((b.y-a.y)||1e-9)+a.x)hit=!hit;}return hit;}
function area(poly:PhysicsPoint[]){let n=0;for(let i=0;i<poly.length;i++){const a=poly[i],b=poly[(i+1)%poly.length];n+=a.x*b.y-b.x*a.y;}return Math.abs(n/2);}
function centroid(poly:PhysicsPoint[]){return poly.reduce((s,p)=>({x:s.x+p.x/poly.length,y:s.y+p.y/poly.length}),{x:0,y:0});}
function nearestPoint(p:PhysicsPoint,a:PhysicsPoint,b:PhysicsPoint){const dx=b.x-a.x,dy=b.y-a.y,l=dx*dx+dy*dy||1,t=clamp(((p.x-a.x)*dx+(p.y-a.y)*dy)/l);return{x:a.x+t*dx,y:a.y+t*dy};}
function distanceToSegment(p:PhysicsPoint,a:PhysicsPoint,b:PhysicsPoint){const n=nearestPoint(p,a,b);return Math.hypot(p.x-n.x,p.y-n.y);}
function edgeDistance(p:PhysicsPoint,poly:PhysicsPoint[]){return Math.min(...poly.map((a,i)=>distanceToSegment(p,a,poly[(i+1)%poly.length])));}
function inward(poly:PhysicsPoint[],index:number){const a=poly[index],b=poly[(index+1)%poly.length],m={x:(a.x+b.x)/2,y:(a.y+b.y)/2},c=centroid(poly),dx=b.x-a.x,dy=b.y-a.y,l=Math.hypot(dx,dy)||1,n1={x:-dy/l,y:dx/l},n2={x:dy/l,y:-dx/l},to={x:c.x-m.x,y:c.y-m.y};return n1.x*to.x+n1.y*to.y>0?n1:n2;}
function pointAcross(poly:PhysicsPoint[],indexes:number[],t:number,offset:number){const usable=indexes.length?indexes:[0];const segments=usable.map(i=>({i,a:poly[i],b:poly[(i+1)%poly.length]}));const lengths=segments.map(s=>Math.hypot(s.b.x-s.a.x,s.b.y-s.a.y));const total=lengths.reduce((a,b)=>a+b,0)||1;let d=clamp(t)*total,segment=segments[segments.length-1],u=1;for(let i=0;i<segments.length;i++){if(d<=lengths[i]){segment=segments[i];u=lengths[i]?d/lengths[i]:0;break;}d-=lengths[i];}const n=inward(poly,segment.i);return{x:segment.a.x+(segment.b.x-segment.a.x)*u+n.x*offset,y:segment.a.y+(segment.b.y-segment.a.y)*u+n.y*offset};}
function bounds(poly:PhysicsPoint[]){const xs=poly.map(p=>p.x),ys=poly.map(p=>p.y);return{minX:Math.min(...xs),maxX:Math.max(...xs),minY:Math.min(...ys),maxY:Math.max(...ys)};}
function randomInside(poly:PhysicsPoint[],random:()=>number,minEdge=0,tries=2400){const b=bounds(poly),c=centroid(poly);for(let i=0;i<tries;i++){const q={x:b.minX+random()*(b.maxX-b.minX),y:b.minY+random()*(b.maxY-b.minY)};if(pointInPolygon(q,poly)&&edgeDistance(q,poly)>=minEdge)return q;}return pointInPolygon(c,poly)?c:poly[0];}
function resolvedPlant(p:RecipePhysicsPlant):RecipePhysicsPlant{const profile=getRecipePhysicsProfile(p.key);const repetition=profile?.repetition??p.repetition??'';const grouping=p.grouping??(/hedge|row/.test(repetition)?'individual':/matrix|mass/.test(repetition)?'continuous-mass':(p.clump??profile?.clumpStrength??0)>=.82?'large-drift':(p.clump??profile?.clumpStrength??0)>=.65?'medium-drift':'individual');return{...p,layer:profile?.role??p.layer,clump:p.clump??profile?.clumpStrength,frontAttraction:p.frontAttraction??profile?.frontAttraction,backAttraction:p.backAttraction??profile?.backAttraction,edgeAttraction:p.edgeAttraction??profile?.edgeAttraction,repetition,spacing:p.spacing??'natural',grouping,groupGap:p.groupGap??'medium'};}
function modeFor(p:RecipePhysicsPlant):RecipePlacementMode{if(p.mode)return p.mode;const repetition=p.repetition||'';if(p.layer==='back'||/hedge|row/.test(repetition))return'back-attract';if(p.layer==='front'||/ribbon|edge/.test(repetition))return'front-fill';if(/matrix|stack/.test(repetition))return'stack';return'scatter';}
function spacingMultiplier(p:RecipePhysicsPlant){return p.spacing==='tight'?.9:p.spacing==='loose'?1.22:1;}
function groupSize(grouping:PlantGrouping,random:()=>number){if(grouping==='individual')return 1;if(grouping==='small-drift')return 3+Math.floor(random()*3);if(grouping==='medium-drift')return 6+Math.floor(random()*5);if(grouping==='large-drift')return 11+Math.floor(random()*8);return 9999;}
function groupGapDiameters(gap:GroupGap,random:()=>number){const range=gap==='small'?[.25,.75]:gap==='large'?[1.5,2.5]:[.75,1.5];return range[0]+random()*(range[1]-range[0]);}
function counts(plants:RecipePhysicsPlant[],total:number){const sum=plants.reduce((a,p)=>a+Math.max(0,p.weight),0)||1;const raw=plants.map(p=>total*Math.max(0,p.weight)/sum),base=raw.map(Math.floor);let left=total-base.reduce((a,b)=>a+b,0);const order=raw.map((v,i)=>({i,r:v-Math.floor(v)})).sort((a,b)=>b.r-a.r||a.i-b.i);for(let i=0;i<left;i++)base[order[i%order.length].i]++;return base;}
function targetCoverage(density:number){return Math.round((.18+clamp(density,.05,1)*.72)*100);}
function estimateCount(options:RecipePhysicsOptions,plants:RecipePhysicsPlant[]){if(typeof options.targetCount==='number')return Math.max(0,Math.round(options.targetCount));if(plants.some(p=>typeof p.count==='number'))return plants.reduce((s,p)=>s+Math.max(0,Math.round(p.count??0)),0);const weights=plants.reduce((s,p)=>s+Math.max(0,p.weight),0)||1;const weightedVisibleArea=plants.reduce((s,p)=>s+Math.PI*p.radius*p.radius*(Math.max(0,p.weight)/weights),0)||1;const target=targetCoverage(options.density??.5)/100;return Math.max(plants.length,Math.ceil(area(options.polygon)*target/weightedVisibleArea));}
function buildDrifts(plants:RecipePhysicsPlant[],plantCounts:number[],poly:PhysicsPoint[],random:()=>number){const centers:Array<{id:string;plantId:number;x:number;y:number;grouping:PlantGrouping;gapDiameters:number}>=[];const expanded:ExpandedPlant[]=[];plants.forEach((plant,plantIndex)=>{const count=plantCounts[plantIndex],grouping=plant.grouping??'individual',size=groupSize(grouping,random),driftCount=grouping==='continuous-mass'?1:Math.max(1,Math.ceil(count/size));const localCenters:PhysicsPoint[]=[];for(let d=0;d<driftCount;d++){let center:PhysicsPoint|null=null;const gap=groupGapDiameters(plant.groupGap??'medium',random);for(let tries=0;tries<600;tries++){const q=randomInside(poly,random,plant.radius+2);const ok=localCenters.every(c=>Math.hypot(q.x-c.x,q.y-c.y)>=plant.radius*2*gap);if(ok){center=q;break;}}center=center??randomInside(poly,random,plant.radius+2);localCenters.push(center);centers.push({id:`${plant.key}:drift:${d}`,plantId:plant.plantId,x:center.x,y:center.y,grouping,gapDiameters:gap});}
 for(let i=0;i<count;i++){const driftIndex=grouping==='continuous-mass'?0:Math.min(localCenters.length-1,Math.floor(i/size));expanded.push({...plant,ordinal:i,driftId:`${plant.key}:drift:${driftIndex}`,driftCenter:localCenters[driftIndex]});}});return{expanded,centers};}
function targetFor(p:ExpandedPlant,totalForPlant:number,poly:PhysicsPoint[],front:number[],back:number[],random:()=>number){const mode=modeFor(p),radius=p.radius,t=(p.ordinal+.5)/Math.max(1,totalForPlant);if(mode==='back-attract')return pointAcross(poly,back,clamp(t+(random()-.5)*.018),radius+4);if(mode==='front-fill'){const depth=p.ordinal%3;return pointAcross(poly,front,clamp(t+(random()-.5)*.035),radius+4+depth*radius*.95);}if(p.driftCenter){const tightness=.25+(1-(p.clump??.5))*.85;return{x:p.driftCenter.x+(random()-.5)*radius*2*tightness,y:p.driftCenter.y+(random()-.5)*radius*2*tightness};}return randomInside(poly,random,radius+3);}
function wall(engine:Matter.Engine,a:PhysicsPoint,b:PhysicsPoint){const dx=b.x-a.x,dy=b.y-a.y;Matter.Composite.add(engine.world,Matter.Bodies.rectangle((a.x+b.x)/2,(a.y+b.y)/2,Math.hypot(dx,dy),8,{isStatic:true,angle:Math.atan2(dy,dx),friction:.35,restitution:0,label:'zone-wall'}));}
function nearestValidPoint(wanted:PhysicsPoint,poly:PhysicsPoint[],minimumEdge:number,random:()=>number){if(pointInPolygon(wanted,poly)&&edgeDistance(wanted,poly)>=minimumEdge)return wanted;let best:PhysicsPoint|null=null,bestScore=Infinity;const b=bounds(poly);for(let i=0;i<2200;i++){const q={x:b.minX+random()*(b.maxX-b.minX),y:b.minY+random()*(b.maxY-b.minY)};if(!pointInPolygon(q,poly)||edgeDistance(q,poly)<minimumEdge)continue;const score=Math.hypot(q.x-wanted.x,q.y-wanted.y);if(score<bestScore){best=q;bestScore=score;}}return best??randomInside(poly,random,minimumEdge);}
function settle(poly:PhysicsPoint[],records:RecordBody[],options:RecipePhysicsOptions,random:()=>number){const engine=Matter.Engine.create({gravity:{x:0,y:0}});poly.forEach((a,i)=>wall(engine,a,poly[(i+1)%poly.length]));records.forEach(r=>Matter.Composite.add(engine.world,r.body));const attraction=Math.max(.1,options.attractionStrength??1),steps=Math.max(220,options.iterations??900);for(let step=0;step<steps;step++){records.forEach(r=>{const mode=modeFor(r.plant),dx=r.target.x-r.body.position.x,dy=r.target.y-r.body.position.y,d=Math.hypot(dx,dy)||1,profile=mode==='back-attract'?(r.plant.backAttraction??2.4):mode==='front-fill'?(r.plant.frontAttraction??1.8):1,base=mode==='back-attract'?.0065:mode==='front-fill'?.0046:r.plant.driftCenter?.0012:.00035;Matter.Body.applyForce(r.body,r.body.position,{x:dx/d*r.body.mass*base*attraction*profile,y:dy/d*r.body.mass*base*attraction*profile});});Matter.Engine.update(engine,1000/120);}for(let i=0;i<120;i++)Matter.Engine.update(engine,1000/120);records.forEach(r=>{const minimum=(r.body.circleRadius||0)+1;if(!pointInPolygon(r.body.position,poly)||edgeDistance(r.body.position,poly)<minimum)Matter.Body.setPosition(r.body,nearestValidPoint(r.target,poly,minimum,random));});Matter.Engine.clear(engine);}
function coverage(placements:RecipePhysicsPlacement[],poly:PhysicsPoint[]){return Math.min(100,Math.round(placements.reduce((s,p)=>s+Math.PI*p.radius*p.radius,0)/Math.max(1,area(poly))*100));}
function overlaps(records:RecordBody[]){let count=0;for(let i=0;i<records.length;i++)for(let j=i+1;j<records.length;j++){const d=Math.hypot(records[i].body.position.x-records[j].body.position.x,records[i].body.position.y-records[j].body.position.y),min=(records[i].body.circleRadius||0)+(records[j].body.circleRadius||0);if(d<min)count++;}return count;}

function runPass(options:RecipePhysicsOptions,seed:number):RecipePhysicsResult{const random=rng(seed),plants=options.plants.filter(p=>p.enabled!==false).map(resolvedPlant),desired=estimateCount(options,plants),explicit=plants.some(p=>typeof p.count==='number'),baseCounts=explicit?plants.map(p=>Math.max(0,Math.round(p.count??0))):counts(plants,desired),target=targetCoverage(options.density??.5),scale=clamp(options.physicsScale??1,1,1.2),allowed=clamp(options.allowedOverlap??.08,0,.35),pad=Math.max(0,options.spacingPad??options.padding??0),front=options.frontEdges||[],back=options.backEdges||[],cycles:RecipePhysicsCycle[]=[];let plantCounts=[...baseCounts],records:RecordBody[]=[],driftCenters:RecipePhysicsResult['diagnostics']['driftCenters']=[],previousCoverage=-1;
 for(let cycle=0;cycle<8;cycle++){const built=buildDrifts(plants,plantCounts,options.polygon,random);driftCenters=built.centers;const expanded=options.dropOrder==='grouped'?built.expanded:shuffle(built.expanded,random);const totals=new Map<number,number>();expanded.forEach(p=>totals.set(p.plantId,(totals.get(p.plantId)||0)+1));records=expanded.map((plant,index)=>{const collisionRadius=Math.max(3,plant.radius*scale*spacingMultiplier(plant)*(1-allowed)),target=targetFor({...plant,radius:collisionRadius},totals.get(plant.plantId)||1,options.polygon,front,back,random),start=nearestValidPoint({x:target.x+(random()-.5)*collisionRadius*.25,y:target.y+(random()-.5)*collisionRadius*.25},options.polygon,collisionRadius+pad,random),body=Matter.Bodies.circle(start.x,start.y,collisionRadius,{friction:.03,frictionAir:.16,restitution:.01,density:.002,label:`recipe:${plant.key}:${index}`});return{body,plant,target,rotationDeg:Math.round(random()*359)};});settle(options.polygon,records,options,random);const valid=records.filter(r=>pointInPolygon(r.body.position,options.polygon));const pruned=records.length-valid.length;records=valid;const placements=records.map(r=>({key:r.plant.key,plantId:r.plant.plantId,layer:r.plant.layer,x:r.body.position.x,y:r.body.position.y,radius:r.plant.radius,rotationDeg:r.rotationDeg,driftId:r.plant.driftId}));const currentCoverage=coverage(placements,options.polygon);const needed=currentCoverage>=target?0:Math.max(1,Math.ceil((target-currentCoverage)/Math.max(1,currentCoverage)*records.length*.7));cycles.push({cycle:cycle+1,requested:plantCounts.reduce((a,b)=>a+b,0),placed:records.length,coverage:currentCoverage,pruned,refilled:needed});if(currentCoverage>=target||currentCoverage===previousCoverage||cycle===7){const meanArea=plants.reduce((s,p)=>s+Math.PI*p.radius*p.radius*(p.weight/(plants.reduce((a,x)=>a+x.weight,0)||1)),0)||1;const capacity=Math.max(plants.length,Math.floor(area(options.polygon)*.9/meanArea));return{placements,diagnostics:{requested:plantCounts.reduce((a,b)=>a+b,0),placed:placements.length,rejected:pruned,unresolvedOverlaps:overlaps(records),seed,capacity,capacityLimited:placements.length<plantCounts.reduce((a,b)=>a+b,0),estimatedCoverage:currentCoverage,passes:1,targetCoverage:target,cycles,driftCenters}};}previousCoverage=currentCoverage;const extra=counts(plants,needed);plantCounts=plantCounts.map((n,i)=>n+extra[i]);}
 throw new Error('Recipe physics failed to complete.');}

export function runRecipePhysics(options:RecipePhysicsOptions):RecipePhysicsResult{if(options.polygon.length<3)throw new Error('Recipe physics requires a polygon with at least three points.');if(!options.plants.some(p=>p.enabled!==false))return{placements:[],diagnostics:{requested:0,placed:0,rejected:0,unresolvedOverlaps:0,seed:options.seed,capacity:0,capacityLimited:false,estimatedCoverage:0,passes:0,targetCoverage:0,cycles:[],driftCenters:[]}};const passes=Math.max(1,Math.min(8,Math.round(options.passes??1)));let best:RecipePhysicsResult|null=null;for(let pass=0;pass<passes;pass++){const result=runPass(options,options.seed+pass*7919);if(!best||result.diagnostics.estimatedCoverage>best.diagnostics.estimatedCoverage||(result.diagnostics.estimatedCoverage===best.diagnostics.estimatedCoverage&&result.diagnostics.unresolvedOverlaps<best.diagnostics.unresolvedOverlaps))best=result;}best!.diagnostics.seed=options.seed;best!.diagnostics.passes=passes;return best!;}
