import type { AppRecipe } from '../data/recipeCatalog';
import type { GardenZone, PlacedPlant, TestLogEntry, TestSnapshot } from '../types/plant';
type Hook={memoizedState?:unknown;queue?:{dispatch?:(value:unknown)=>void}|null;next?:Hook|null};
type Fiber={child?:Fiber|null;sibling?:Fiber|null;return?:Fiber|null;memoizedState?:Hook|null};
type DebugHooks={log:(value:unknown)=>void;snapshots:(value:unknown)=>void};
let cachedHooks:DebugHooks|null=null;
const id=(prefix:string)=>`${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,10)}`;
function fiberOf(element:Element|null):Fiber|null{let current=element;while(current){const key=Object.keys(current).find(name=>name.startsWith('__reactFiber$'));if(key)return(current as unknown as Record<string,Fiber>)[key]||null;current=current.parentElement;}return null;}
function rootOf(start:Fiber|null){let root=start;if(!root)return null;while(root.return)root=root.return;return root;}
function hooksFor(element:Element|null):DebugHooks|null{const root=rootOf(fiberOf(element));if(!root)return null;const stack=[root],seen=new Set<Fiber>();while(stack.length){const fiber=stack.pop()!;if(seen.has(fiber))continue;seen.add(fiber);let hook=fiber.memoizedState||null;while(hook){const state=hook.memoizedState;const testLog=Array.isArray(state)&&state.some(item=>!!item&&typeof item==='object'&&'action'in item&&'timestamp'in item);if(testLog&&hook.queue?.dispatch&&hook.next?.queue?.dispatch)return{log:hook.queue.dispatch,snapshots:hook.next.queue.dispatch};hook=hook.next||null;}if(fiber.sibling)stack.push(fiber.sibling);if(fiber.child)stack.push(fiber.child);}return null;}
export function recordRecipeDebug(host:HTMLElement,action:string,details:Record<string,unknown>,snapshot?:TestSnapshot){const hooks=cachedHooks||(cachedHooks=hooksFor(host));if(!hooks){console.warn('Recipe debug bridge could not find app debug state',{action,details});return false;}const entry:TestLogEntry={id:id('recipe-log'),timestamp:new Date().toISOString(),action,details};hooks.log((previous:TestLogEntry[])=>[...previous.slice(-999),entry]);if(snapshot)hooks.snapshots((previous:TestSnapshot[])=>[...previous,snapshot]);return true;}
const color=(plantId:number)=>`hsl(${Math.abs((plantId*137.508)%360).toFixed(1)} 58% 48%)`;
export function recipeSnapshot(runId:string,recipe:AppRecipe,zone:GardenZone,placements:PlacedPlant[],details:Record<string,unknown>):TestSnapshot{const padding=45,xs=zone.points.map(p=>p.x),ys=zone.points.map(p=>p.y),minX=Math.min(...xs)-padding,minY=Math.min(...ys)-padding,maxX=Math.max(...xs)+padding,maxY=Math.max(...ys)+padding,width=Math.max(220,maxX-minX),height=Math.max(180,maxY-minY),scale=Math.min(1.2,760/Math.max(width,height)),canvas=document.createElement('canvas');canvas.width=Math.max(220,Math.round(width*scale));canvas.height=Math.max(180,Math.round(height*scale));const c=canvas.getContext('2d'),tx=(x:number)=>(x-minX)*scale,ty=(y:number)=>(y-minY)*scale;if(c){c.fillStyle='#f8fafc';c.fillRect(0,0,canvas.width,canvas.height);c.beginPath();zone.points.forEach((p,i)=>i?c.lineTo(tx(p.x),ty(p.y)):c.moveTo(tx(p.x),ty(p.y)));c.closePath();c.fillStyle='rgba(34,197,94,.14)';c.strokeStyle='#15803d';c.lineWidth=2;c.fill();c.stroke();const edges=(indexes:number[],stroke:string)=>indexes.forEach(index=>{const a=zone.points[index],b=zone.points[(index+1)%zone.points.length];c.beginPath();c.moveTo(tx(a.x),ty(a.y));c.lineTo(tx(b.x),ty(b.y));c.strokeStyle=stroke;c.lineWidth=6;c.stroke();});edges(zone.edgeRoles?.front||[],'#2563eb');edges(zone.edgeRoles?.back||[],'#dc2626');placements.forEach(item=>{const radius=Math.max(5,((item.displayWidthFt||2)*20*scale)/2);c.beginPath();c.arc(tx(item.x),ty(item.y),radius,0,Math.PI*2);c.fillStyle=color(item.plantId);c.globalAlpha=.52;c.fill();c.globalAlpha=1;c.strokeStyle='#0f172a';c.lineWidth=1;c.stroke();});c.fillStyle='rgba(255,255,255,.92)';c.fillRect(8,8,Math.min(canvas.width-16,520),48);c.fillStyle='#111827';c.font='bold 12px system-ui,sans-serif';c.fillText(`${recipe.name} · ${placements.length} placed`,15,17);c.font='11px system-ui,sans-serif';c.fillStyle='#475569';c.fillText(`Run ${runId} · front blue · back red`,15,35);}return{id:id('recipe-snapshot'),timestamp:new Date().toISOString(),reason:'recipe.generation.completed',imageDataUrl:canvas.toDataURL('image/jpeg',.7),width:canvas.width,height:canvas.height,details};}
export function edgeDebug(zone:GardenZone,indexes:number[]){return indexes.map(index=>{const start=zone.points[index],end=zone.points[(index+1)%zone.points.length];return{index,start,end,lengthPx:Math.hypot(end.x-start.x,end.y-start.y)};});}
function segmentDistance(point:{x:number;y:number},a:{x:number;y:number},b:{x:number;y:number}){const dx=b.x-a.x,dy=b.y-a.y,l=dx*dx+dy*dy||1,t=Math.max(0,Math.min(1,((point.x-a.x)*dx+(point.y-a.y)*dy)/l));return Math.hypot(point.x-(a.x+t*dx),point.y-(a.y+t*dy));}
export function nearestRoleEdge(point:{x:number;y:number},zone:GardenZone,indexes:number[]){return indexes.length?Math.min(...indexes.map(index=>segmentDistance(point,zone.points[index],zone.points[(index+1)%zone.points.length]))):null;}
export const recipeRunId=()=>id('recipe-run');
