import { useEffect, useMemo, useState } from 'react';
import { createPortal } from 'react-dom';
import App from './App';
import { recipeCatalog, type AppRecipe } from './data/recipeCatalog';
import { runRecipePhysics, type RecipeLayoutBehavior, type RecipePhysicsLayer } from './engine/recipePhysicsEngine';
import type { GardenPlan, GardenZone, PlacedPlant, PlantingGroup } from './types/plant';

const CURRENT_PLAN_KEY='garden-planner-current';
type HookNode={memoizedState?:unknown;queue?:{dispatch?:(value:unknown)=>void}|null;next?:HookNode|null};
type FiberNode={child?:FiberNode|null;sibling?:FiberNode|null;return?:FiberNode|null;memoizedProps?:Record<string,unknown>|null;pendingProps?:Record<string,unknown>|null;memoizedState?:HookNode|null};
type PlantControl={plantId:number;name:string;enabled:boolean;weight:number;count:number|null;layer:RecipePhysicsLayer;widthInches:number;clump:number};
type ControlState={seed:number;density:number;targetCount:number|null;layoutBehavior:RecipeLayoutBehavior;allowedOverlap:number;padding:number;iterations:number;passes:number;attractionStrength:number;clumpStrength:number;keepCentersInside:boolean;replaceExisting:boolean;plants:PlantControl[]};

function findFiber(element:Element|null):FiberNode|null{let current=element;while(current){const key=Object.keys(current).find(name=>name.startsWith('__reactFiber$'));if(key)return (current as unknown as Record<string,FiberNode>)[key]||null;current=current.parentElement;}return null;}
function rootOf(start:FiberNode|null){let root=start;if(!root)return null;while(root.return)root=root.return;return root;}
function findCallback(start:FiberNode|null,name:string):((plan:GardenPlan)=>void)|null{const root=rootOf(start);if(!root)return null;const stack=[root],seen=new Set<FiberNode>();while(stack.length){const fiber=stack.pop()!;if(seen.has(fiber))continue;seen.add(fiber);const callback=fiber.memoizedProps?.[name]??fiber.pendingProps?.[name];if(typeof callback==='function')return callback as (plan:GardenPlan)=>void;if(fiber.sibling)stack.push(fiber.sibling);if(fiber.child)stack.push(fiber.child);}return null;}
function applyPlan(host:HTMLElement,plan:GardenPlan){const callback=findCallback(findFiber(host),'onImportPlan')||findCallback(findFiber(host),'onLoadPlan');if(!callback)return false;callback(plan);return true;}
function readPlan():Partial<GardenPlan>|null{try{const raw=localStorage.getItem(CURRENT_PLAN_KEY);return raw?JSON.parse(raw) as Partial<GardenPlan>:null;}catch{return null;}}
function controlsFor(recipe:AppRecipe,zone?:GardenZone):ControlState{return{seed:zone?.plantingSeed||Math.floor(Math.random()*99999)+1,density:zone?.density??recipe.defaultDensity,targetCount:null,layoutBehavior:recipe.layoutBehavior,allowedOverlap:Math.round(recipe.allowedOverlap*100),padding:5,iterations:520,passes:3,attractionStrength:recipe.attractionStrength,clumpStrength:recipe.clumpStrength,keepCentersInside:true,replaceExisting:true,plants:recipe.plants.map(item=>({plantId:item.plantId,name:item.name,enabled:true,weight:item.weight,count:null,layer:item.layer,widthInches:item.widthInches,clump:item.clump}))};}
const input='mt-1 w-full rounded-lg border border-slate-700 bg-slate-900 px-2 py-1.5 text-xs text-white';

function RecipePanel({host}:{host:HTMLElement}){
  const [selectedId,setSelectedId]=useState(recipeCatalog[0]?.id||'');
  const [message,setMessage]=useState('');
  const selectedRecipe=useMemo(()=>recipeCatalog.find(recipe=>recipe.id===selectedId),[selectedId]);
  const currentZone=useMemo(()=>{const plan=readPlan();const modal=host.closest('div.fixed')||host.parentElement?.parentElement;const name=modal?.querySelector('h3')?.textContent?.trim();return ((plan?.zones||[]) as GardenZone[]).find(zone=>zone.name===name);},[host,selectedId]);
  const [controls,setControls]=useState<ControlState>(()=>selectedRecipe?controlsFor(selectedRecipe,currentZone):{seed:1,density:50,targetCount:null,layoutBehavior:'natural',allowedOverlap:8,padding:5,iterations:520,passes:3,attractionStrength:1,clumpStrength:1,keepCentersInside:true,replaceExisting:true,plants:[]});
  useEffect(()=>{if(selectedRecipe){setControls(controlsFor(selectedRecipe,currentZone));setMessage('');}},[selectedRecipe,currentZone?.id]);
  const updatePlant=(plantId:number,updates:Partial<PlantControl>)=>setControls(value=>({...value,plants:value.plants.map(item=>item.plantId===plantId?{...item,...updates}:item)}));
  const generate=(newSeed=false)=>{
    if(!selectedRecipe)return;const plan=readPlan();if(!plan){setMessage('No current plan was found.');return;}
    const modal=host.closest('div.fixed')||host.parentElement?.parentElement;const zoneName=modal?.querySelector('h3')?.textContent?.trim();const zones=(plan.zones||[]) as GardenZone[];const zone=zones.find(item=>item.name===zoneName);if(!zone||zone.points.length<3){setMessage('The selected planting zone could not be found.');return;}
    const seed=newSeed?Math.floor(Math.random()*99999)+1:controls.seed;if(newSeed)setControls(value=>({...value,seed}));const pixelsPerFoot=plan.scalePixelsPerFoot||20;const active=controls.plants.filter(item=>item.enabled);
    const physics=runRecipePhysics({polygon:zone.points,seed,density:controls.density/100,targetCount:controls.targetCount??undefined,frontEdges:zone.edgeRoles?.front,backEdges:zone.edgeRoles?.back,iterations:controls.iterations,passes:controls.passes,padding:controls.padding,allowedOverlap:controls.allowedOverlap/100,attractionStrength:controls.attractionStrength,clumpStrength:controls.clumpStrength,layoutBehavior:controls.layoutBehavior,keepCentersInside:controls.keepCentersInside,plants:active.map(item=>({key:`${selectedRecipe.id}:${item.plantId}`,plantId:item.plantId,layer:item.layer,weight:item.weight,count:item.count??undefined,enabled:item.enabled,radius:Math.max(5,(item.widthInches/12)*pixelsPerFoot/2),clump:item.clump}))});
    const byId=new Map(active.map(item=>[item.plantId,item]));const generated:PlacedPlant[]=physics.placements.map(item=>({instanceId:`${Date.now().toString(36)}${Math.random().toString(36).slice(2)}`,plantId:item.plantId,x:item.x,y:item.y,zone:zone.id,notes:`Recipe: ${selectedRecipe.name}`,displayMode:'symbol',customColor:null,itemType:'plant',rotationDeg:item.rotationDeg,displayWidthFt:(byId.get(item.plantId)?.widthInches||24)/12}));
    const groupId=`recipe-${zone.id}`;const group:PlantingGroup={id:groupId,name:`Recipe · ${selectedRecipe.name}`,notes:selectedRecipe.designIntent,plantIds:[...new Set(active.map(item=>item.plantId))]};const plantingGroups=[...((plan.plantingGroups||[]) as PlantingGroup[]).filter(item=>item.id!==groupId&&item.id!==zone.plantingGroupId),group];const nextZones=zones.map(item=>item.id===zone.id?{...item,density:controls.density,plantingGroupId:groupId,plantingGroupName:group.name,plantingRecipeId:selectedRecipe.id,plantingRecipeName:selectedRecipe.name,plantingSeed:seed,plantingType:'flowerBed' as const,layoutMode:'fill' as const,plantVariety:'low' as const}:item);const existing=(plan.placedPlants||[]) as PlacedPlant[];const placedPlants=controls.replaceExisting?[...existing.filter(item=>item.zone!==zone.id||item.itemType==='rock'),...generated]:[...existing,...generated];
    const nextPlan:GardenPlan={id:plan.id||'current-plan',name:plan.name||'My Garden Plan',createdAt:plan.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString(),backgroundImage:plan.backgroundImage??null,backgroundOpacity:plan.backgroundOpacity??.5,backgroundLocked:plan.backgroundLocked??false,scalePixelsPerFoot:plan.scalePixelsPerFoot??null,placedPlants,zones:nextZones,plantingGroups,zoneShapesVisible:plan.zoneShapesVisible,notes:plan.notes||'',canvasWorldSize:plan.canvasWorldSize,plantCircleOpacity:plan.plantCircleOpacity,plantLabelMode:plan.plantLabelMode,plantClumpingEnabled:plan.plantClumpingEnabled,plantClumpStrength:plan.plantClumpStrength,zoom:plan.zoom,shrubScore:plan.shrubScore,restoreBackgroundOnLaunch:plan.restoreBackgroundOnLaunch};
    if(!applyPlan(host,nextPlan)){setMessage('The running app could not accept the recipe.');return;}setMessage(`${selectedRecipe.name}: ${generated.length} plants placed · seed ${seed}.`);
  };
  if(!selectedRecipe)return null;
  return createPortal(<section className="rounded-2xl border border-violet-500/50 bg-violet-950/25 p-3 text-slate-100"><div className="text-[10px] font-extrabold uppercase tracking-[.17em] text-violet-300">Plant recipe engine</div><div className="mt-1 text-sm font-bold">Recipe controls</div><label className="mt-3 block text-xs text-slate-300">Recipe<select value={selectedId} onChange={e=>setSelectedId(e.target.value)} className={input}>{recipeCatalog.map(recipe=><option key={recipe.id} value={recipe.id}>{recipe.name}</option>)}</select></label><div className="mt-2 rounded-lg border border-violet-500/20 bg-slate-950/40 p-2 text-[11px] text-slate-300">{selectedRecipe.designIntent}</div><div className="mt-3 grid grid-cols-2 gap-2"><label className="text-xs">Seed<input type="number" value={controls.seed} onChange={e=>setControls(v=>({...v,seed:Number(e.target.value)||1}))} className={input}/></label><label className="text-xs">Layout<select value={controls.layoutBehavior} onChange={e=>setControls(v=>({...v,layoutBehavior:e.target.value as RecipeLayoutBehavior}))} className={input}><option value="natural">Natural drift</option><option value="clumps">Tighter clumps</option><option value="even">Even spacing</option><option value="stacked">Stacked/orderly</option><option value="spread">Spread to fill</option></select></label></div><label className="mt-3 block text-xs">Fullness: {controls.density}%<input type="range" min="5" max="100" value={controls.density} onChange={e=>setControls(v=>({...v,density:Number(e.target.value)}))} className="mt-1 w-full"/></label><div className="mt-3 space-y-2">{controls.plants.map(item=><div key={item.plantId} className="rounded-xl border border-slate-700/80 bg-slate-950/45 p-2"><div className="flex items-center gap-2"><input type="checkbox" checked={item.enabled} onChange={e=>updatePlant(item.plantId,{enabled:e.target.checked})}/><div className="min-w-0 flex-1 truncate text-xs font-bold">{item.name}</div><span className="text-[10px] text-slate-400">{item.layer} · {item.weight}%</span></div></div>)}</div><div className="mt-3 grid grid-cols-2 gap-2"><button type="button" onClick={()=>generate(false)} className="rounded-xl bg-violet-600 px-3 py-2.5 text-sm font-bold">Generate</button><button type="button" onClick={()=>generate(true)} className="rounded-xl bg-fuchsia-700 px-3 py-2.5 text-sm font-bold">New seed + generate</button></div><button type="button" onClick={()=>setControls(controlsFor(selectedRecipe,currentZone))} className="mt-2 w-full rounded-lg border border-slate-700 bg-slate-900 px-2 py-2 text-xs font-bold">Restore recipe defaults</button>{message&&<div className="mt-2 rounded-lg border border-slate-700 bg-slate-900 px-2 py-2 text-xs">{message}</div>}</section>,host);
}

export default function RecipeAppIntegration(){const [host,setHost]=useState<HTMLElement|null>(null);useEffect(()=>{let frame=0;const find=()=>{const label=[...document.querySelectorAll('label')].find(item=>item.textContent?.trim()==='Planting type');const card=label?.closest('div.rounded-2xl');const parent=card?.parentElement;if(!card||!parent){setHost(null);return;}let recipeHost=parent.querySelector<HTMLElement>('[data-recipe-react-host]');if(!recipeHost){recipeHost=document.createElement('div');recipeHost.dataset.recipeReactHost='true';parent.insertBefore(recipeHost,card);}setHost(recipeHost);};const observer=new MutationObserver(()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(find);});observer.observe(document.body,{childList:true,subtree:true});find();return()=>{observer.disconnect();cancelAnimationFrame(frame);};},[]);return <><App/>{host&&<RecipePanel host={host}/>}</>;}
