import { useEffect, useMemo, useState } from 'react';
import { createPortal } from 'react-dom';
import App from './App';
import { recipeCatalog } from './data/recipeCatalog';
import { runRecipePhysics, type RecipeLayoutBehavior, type RecipePhysicsLayer } from './engine/recipePhysicsEngine';
import type { GardenPlan, GardenZone, PlacedPlant, PlantingGroup, TestSnapshot } from './types/plant';

const CURRENT_PLAN_KEY = 'garden-planner-current';
const RECIPE_DEBUG_HISTORY_KEY = 'plant-pending-recipe-generation-history';
const RECIPE_PRESETS_KEY = 'plant-pending-recipe-control-presets';

type HookNode = { memoizedState?: unknown; queue?: { dispatch?: (value: unknown) => void } | null; next?: HookNode | null };
type FiberNode = { child?: FiberNode | null; sibling?: FiberNode | null; return?: FiberNode | null; memoizedProps?: Record<string, unknown> | null; pendingProps?: Record<string, unknown> | null; memoizedState?: HookNode | null };
type PlantControl = { plantId: number; name: string; enabled: boolean; weight: number; count: number | null; layer: RecipePhysicsLayer; widthInches: number; clump: number };
type ControlState = {
  seed: number; density: number; targetCount: number | null; layoutBehavior: RecipeLayoutBehavior;
  allowedOverlap: number; padding: number; iterations: number; passes: number;
  attractionStrength: number; clumpStrength: number; keepCentersInside: boolean; replaceExisting: boolean;
  plants: PlantControl[];
};
type ResultState = { requested: number; placed: number; rejected: number; overlaps: number; coverage: number; capacity: number; capacityLimited: boolean; seed: number; passes: number };

function findReactFiber(element: Element | null): FiberNode | null {
  let current: Element | null = element;
  while (current) { const key = Object.keys(current).find(name => name.startsWith('__reactFiber$')); if (key) return (current as unknown as Record<string, FiberNode>)[key] || null; current = current.parentElement; }
  return null;
}
function fiberRoot(start: FiberNode | null): FiberNode | null { if (!start) return null; let root = start; while (root.return) root = root.return; return root; }
function findCallbackInFiber(start: FiberNode | null, callbackName: string): ((plan: GardenPlan) => void) | null {
  const root = fiberRoot(start); if (!root) return null; const stack: FiberNode[] = [root]; const visited = new Set<FiberNode>();
  while (stack.length) { const fiber = stack.pop()!; if (visited.has(fiber)) continue; visited.add(fiber); const memoized = fiber.memoizedProps?.[callbackName]; if (typeof memoized === 'function') return memoized as (plan: GardenPlan) => void; const pending = fiber.pendingProps?.[callbackName]; if (typeof pending === 'function') return pending as (plan: GardenPlan) => void; if (fiber.sibling) stack.push(fiber.sibling); if (fiber.child) stack.push(fiber.child); }
  return null;
}
function applyPlanToRunningApp(host: HTMLElement, plan: GardenPlan): boolean { const apply = findCallbackInFiber(findReactFiber(host), 'onImportPlan') || findCallbackInFiber(findReactFiber(host), 'onLoadPlan'); if (!apply) return false; apply(plan); return true; }
function appendDebugSnapshotToRunningApp(host: HTMLElement, snapshot: TestSnapshot): boolean {
  const root = fiberRoot(findReactFiber(host)); if (!root) return false; const stack: FiberNode[] = [root]; const visited = new Set<FiberNode>();
  while (stack.length) { const fiber = stack.pop()!; if (visited.has(fiber)) continue; visited.add(fiber); const snapshotsProp = fiber.memoizedProps?.debugSnapshots; if (Array.isArray(snapshotsProp)) { let owner: FiberNode | null | undefined = fiber; while (owner) { let hook = owner.memoizedState; while (hook) { if (hook.memoizedState === snapshotsProp && typeof hook.queue?.dispatch === 'function') { hook.queue.dispatch([...(snapshotsProp as TestSnapshot[]).slice(-99), snapshot]); return true; } hook = hook.next; } owner = owner.return; } } if (fiber.sibling) stack.push(fiber.sibling); if (fiber.child) stack.push(fiber.child); }
  return false;
}
function persistRecipeDebugSnapshot(snapshot: TestSnapshot): void { try { const parsed = JSON.parse(localStorage.getItem(RECIPE_DEBUG_HISTORY_KEY) || '[]'); const history = Array.isArray(parsed) ? parsed : []; localStorage.setItem(RECIPE_DEBUG_HISTORY_KEY, JSON.stringify([...history.slice(-99), snapshot])); } catch { /* debug must not block generation */ } }
function readPlan(): Partial<GardenPlan> | null { try { const raw = localStorage.getItem(CURRENT_PLAN_KEY); return raw ? JSON.parse(raw) as Partial<GardenPlan> : null; } catch { return null; } }
function defaultControls(recipe: (typeof recipeCatalog)[number], zone?: GardenZone): ControlState {
  return { seed: zone?.plantingSeed || Math.floor(Math.random() * 99999), density: zone?.density ?? 50, targetCount: null, layoutBehavior: 'natural', allowedOverlap: 8, padding: 5, iterations: 520, passes: 3, attractionStrength: 1, clumpStrength: 1, keepCentersInside: true, replaceExisting: true, plants: recipe.plants.map(item => ({ plantId: item.plantId, name: item.name, enabled: true, weight: item.weight, count: null, layer: item.layer, widthInches: item.widthInches, clump: item.clump })) };
}
function createRecipeDebugImage(zone: GardenZone, placements: ReturnType<typeof runRecipePhysics>['placements']) {
  const bounds = { minX: Math.min(...zone.points.map(p => p.x)), minY: Math.min(...zone.points.map(p => p.y)), maxX: Math.max(...zone.points.map(p => p.x)), maxY: Math.max(...zone.points.map(p => p.y)) }; const padding = 30;
  const sourceWidth = Math.max(160, bounds.maxX - bounds.minX + padding * 2); const sourceHeight = Math.max(120, bounds.maxY - bounds.minY + padding * 2); const scale = Math.min(1, 720 / Math.max(sourceWidth, sourceHeight));
  const canvas = document.createElement('canvas'); canvas.width = Math.max(220, Math.round(sourceWidth * scale)); canvas.height = Math.max(180, Math.round(sourceHeight * scale)); const context = canvas.getContext('2d'); if (!context) return { imageDataUrl: '', width: 0, height: 0 };
  const x = (value: number) => (value - bounds.minX + padding) * scale; const y = (value: number) => (value - bounds.minY + padding) * scale;
  context.fillStyle = '#f3f4f6'; context.fillRect(0, 0, canvas.width, canvas.height); context.beginPath(); zone.points.forEach((p, i) => i ? context.lineTo(x(p.x), y(p.y)) : context.moveTo(x(p.x), y(p.y))); context.closePath(); context.fillStyle = 'rgba(34,197,94,.14)'; context.strokeStyle = '#15803d'; context.lineWidth = 2; context.fill(); context.stroke();
  const colors: Record<string, string> = { front: '#14b8a6', middle: '#60a5fa', back: '#15803d', accent: '#db2777' }; placements.forEach(p => { context.beginPath(); context.arc(x(p.x), y(p.y), Math.max(3, p.radius * scale), 0, Math.PI * 2); context.fillStyle = colors[p.layer] || '#64748b'; context.globalAlpha = .62; context.fill(); context.globalAlpha = 1; context.strokeStyle = '#0f172a'; context.stroke(); });
  return { imageDataUrl: canvas.toDataURL('image/jpeg', .62), width: canvas.width, height: canvas.height };
}
function buildOverlapWarnings(placements: PlacedPlant[], controls: ControlState, pixelsPerFoot: number) {
  const byId = new Map(controls.plants.map(item => [item.plantId, item])); const warnings: Array<Record<string, unknown>> = []; const allowed = controls.allowedOverlap / 100;
  for (let i = 0; i < placements.length; i += 1) { const a = placements[i]; const ar = byId.get(a.plantId); if (!ar) continue; const aRadius = Math.max(5, (ar.widthInches / 12) * pixelsPerFoot / 2);
    for (let j = i + 1; j < placements.length; j += 1) { const b = placements[j]; const br = byId.get(b.plantId); if (!br) continue; const bRadius = Math.max(5, (br.widthInches / 12) * pixelsPerFoot / 2); const distance = Math.hypot(a.x - b.x, a.y - b.y); const threshold = aRadius + bRadius; const overlapPercent = (threshold - distance) / threshold; if (overlapPercent <= allowed) continue;
      warnings.push({ id: `recipe-overlap-${a.instanceId}-${b.instanceId}`, type: 'overlap', severity: 'warning', message: `${ar.name} overlaps with ${br.name}`, plantIds: [a.plantId, b.plantId], instanceIds: [a.instanceId, b.instanceId], plantNames: [ar.name, br.name], distancePx: distance, overlapThresholdPx: threshold, overlapPx: threshold - distance, overlapPercent: Math.round(overlapPercent * 1000) / 10, positions: [{ x: a.x, y: a.y }, { x: b.x, y: b.y }], displayWidthsFt: [ar.widthInches / 12, br.widthInches / 12] });
    }
  }
  return warnings;
}

const inputClass = 'mt-1 w-full rounded-lg border border-slate-700 bg-slate-900 px-2 py-1.5 text-xs text-white';
const buttonClass = 'rounded-lg border border-slate-700 bg-slate-900 px-2 py-1.5 text-xs font-bold text-slate-100 hover:bg-slate-800';

function RecipePanel({ host }: { host: HTMLElement }) {
  const [selectedId, setSelectedId] = useState(recipeCatalog[0]?.id || ''); const [message, setMessage] = useState(''); const [result, setResult] = useState<ResultState | null>(null); const [advancedOpen, setAdvancedOpen] = useState(false); const [presetName, setPresetName] = useState('');
  const selectedRecipe = useMemo(() => recipeCatalog.find(recipe => recipe.id === selectedId), [selectedId]);
  const currentZone = useMemo(() => { const plan = readPlan(); const modal = host.closest('div.fixed') || host.parentElement?.parentElement; const zoneName = modal?.querySelector('h3')?.textContent?.trim(); return ((plan?.zones || []) as GardenZone[]).find(item => item.name === zoneName); }, [host, selectedId]);
  const [controls, setControls] = useState<ControlState>(() => selectedRecipe ? defaultControls(selectedRecipe, currentZone) : { seed: 1, density: 50, targetCount: null, layoutBehavior: 'natural', allowedOverlap: 8, padding: 5, iterations: 520, passes: 3, attractionStrength: 1, clumpStrength: 1, keepCentersInside: true, replaceExisting: true, plants: [] });
  useEffect(() => { if (selectedRecipe) { setControls(defaultControls(selectedRecipe, currentZone)); setResult(null); setMessage(''); } }, [selectedRecipe, currentZone?.id]);
  const updatePlant = (plantId: number, updates: Partial<PlantControl>) => setControls(value => ({ ...value, plants: value.plants.map(item => item.plantId === plantId ? { ...item, ...updates } : item) }));
  const randomizeSeed = () => setControls(value => ({ ...value, seed: Math.floor(Math.random() * 99999) + 1 }));
  const savePreset = () => { if (!presetName.trim()) { setMessage('Give the preset a name first.'); return; } try { const saved = JSON.parse(localStorage.getItem(RECIPE_PRESETS_KEY) || '{}'); saved[`${selectedId}:${presetName.trim()}`] = controls; localStorage.setItem(RECIPE_PRESETS_KEY, JSON.stringify(saved)); setMessage(`Saved preset “${presetName.trim()}”.`); } catch { setMessage('Preset could not be saved.'); } };
  const loadPreset = () => { try { const saved = JSON.parse(localStorage.getItem(RECIPE_PRESETS_KEY) || '{}'); const preset = saved[`${selectedId}:${presetName.trim()}`] as ControlState | undefined; if (!preset) { setMessage('That preset was not found for this recipe.'); return; } setControls(preset); setMessage(`Loaded preset “${presetName.trim()}”.`); } catch { setMessage('Preset could not be loaded.'); } };
  const generate = (newSeed = false) => {
    setMessage(''); if (!selectedRecipe) return; const plan = readPlan(); if (!plan) { setMessage('No current plan was found.'); return; }
    const modal = host.closest('div.fixed') || host.parentElement?.parentElement; const zoneName = modal?.querySelector('h3')?.textContent?.trim(); const zones = (plan.zones || []) as GardenZone[]; const zone = zones.find(item => item.name === zoneName); if (!zone || zone.points.length < 3) { setMessage('The selected planting zone could not be found.'); return; }
    const runSeed = newSeed ? Math.floor(Math.random() * 99999) + 1 : controls.seed; if (newSeed) setControls(value => ({ ...value, seed: runSeed })); const pixelsPerFoot = plan.scalePixelsPerFoot || 20;
    const activePlants = controls.plants.filter(item => item.enabled); const physicsInputs = activePlants.map(item => ({ key: `${selectedRecipe.id}:${item.plantId}`, plantId: item.plantId, layer: item.layer, weight: item.weight, count: item.count ?? undefined, enabled: item.enabled, radius: Math.max(5, (item.widthInches / 12) * pixelsPerFoot / 2), clump: item.clump }));
    const physics = runRecipePhysics({ polygon: zone.points, seed: runSeed, density: controls.density / 100, targetCount: controls.targetCount ?? undefined, frontEdges: zone.edgeRoles?.front, backEdges: zone.edgeRoles?.back, iterations: controls.iterations, passes: controls.passes, padding: controls.padding, allowedOverlap: controls.allowedOverlap / 100, attractionStrength: controls.attractionStrength, clumpStrength: controls.clumpStrength, layoutBehavior: controls.layoutBehavior, keepCentersInside: controls.keepCentersInside, plants: physicsInputs });
    const byId = new Map(activePlants.map(item => [item.plantId, item])); const generated: PlacedPlant[] = physics.placements.map(item => ({ instanceId: `${Date.now().toString(36)}${Math.random().toString(36).slice(2)}`, plantId: item.plantId, x: item.x, y: item.y, zone: zone.id, notes: `Recipe: ${selectedRecipe.name}`, displayMode: 'symbol', customColor: null, itemType: 'plant', rotationDeg: item.rotationDeg, displayWidthFt: (byId.get(item.plantId)?.widthInches || 24) / 12 }));
    const previousZonePlants = ((plan.placedPlants || []) as PlacedPlant[]).filter(item => item.zone === zone.id); const overlapWarnings = buildOverlapWarnings(generated, controls, pixelsPerFoot); const groupId = `recipe-${zone.id}`;
    const group: PlantingGroup = { id: groupId, name: `Recipe · ${selectedRecipe.name}`, notes: 'Generated with adjustable recipe physics controls.', plantIds: [...new Set(activePlants.map(item => item.plantId))] };
    const plantingGroups = [...((plan.plantingGroups || []) as PlantingGroup[]).filter(item => item.id !== groupId && item.id !== zone.plantingGroupId), group];
    const nextZones = zones.map(item => item.id === zone.id ? { ...item, density: controls.density, plantingGroupId: groupId, plantingGroupName: group.name, plantingRecipeId: selectedRecipe.id, plantingRecipeName: selectedRecipe.name, plantingSeed: runSeed, plantingType: 'flowerBed' as const, layoutMode: 'fill' as const, plantVariety: 'low' as const } : item);
    const existing = (plan.placedPlants || []) as PlacedPlant[]; const placedPlants = controls.replaceExisting ? [...existing.filter(item => item.zone !== zone.id || item.itemType === 'rock'), ...generated] : [...existing, ...generated];
    const nextPlan: GardenPlan = { id: plan.id || 'current-plan', name: plan.name || 'My Garden Plan', createdAt: plan.createdAt || new Date().toISOString(), updatedAt: new Date().toISOString(), backgroundImage: plan.backgroundImage ?? null, backgroundOpacity: plan.backgroundOpacity ?? .5, backgroundLocked: plan.backgroundLocked ?? false, scalePixelsPerFoot: plan.scalePixelsPerFoot ?? null, placedPlants, zones: nextZones, plantingGroups, zoneShapesVisible: plan.zoneShapesVisible, notes: plan.notes || '', canvasWorldSize: plan.canvasWorldSize, plantCircleOpacity: plan.plantCircleOpacity, plantLabelMode: plan.plantLabelMode, plantClumpingEnabled: plan.plantClumpingEnabled, plantClumpStrength: plan.plantClumpStrength, zoom: plan.zoom, shrubScore: plan.shrubScore, restoreBackgroundOnLaunch: plan.restoreBackgroundOnLaunch };
    if (!applyPlanToRunningApp(host, nextPlan)) { setMessage('The running app could not accept the recipe.'); return; }
    const image = createRecipeDebugImage(zone, physics.placements); const snapshot: TestSnapshot = { id: `recipe-${selectedRecipe.id}-${Date.now().toString(36)}`, timestamp: new Date().toISOString(), reason: 'recipe.physics.completed', imageDataUrl: image.imageDataUrl, width: image.width, height: image.height, details: { recipeId: selectedRecipe.id, recipeName: selectedRecipe.name, controls, zone: { id: zone.id, name: zone.name, points: zone.points, density: controls.density, seed: runSeed, frontEdges: zone.edgeRoles?.front || [], backEdges: zone.edgeRoles?.back || [] }, physicsInputs, physicsDiagnostics: physics.diagnostics, placements: physics.placements, generatedPlacedPlants: generated, overlapWarnings, warningSummary: { total: overlapWarnings.length, physicsUnresolvedOverlaps: physics.diagnostics.unresolvedOverlaps }, replacedZonePlants: controls.replaceExisting ? previousZonePlants : [], planCountsAfterGeneration: { placedPlants: placedPlants.length, zones: nextZones.length, plantingGroups: plantingGroups.length } } };
    persistRecipeDebugSnapshot(snapshot); const captured = appendDebugSnapshotToRunningApp(host, snapshot); setResult({ requested: physics.diagnostics.requested, placed: physics.diagnostics.placed, rejected: physics.diagnostics.rejected, overlaps: overlapWarnings.length, coverage: physics.diagnostics.estimatedCoverage, capacity: physics.diagnostics.capacity, capacityLimited: physics.diagnostics.capacityLimited, seed: runSeed, passes: physics.diagnostics.passes }); setMessage(`${selectedRecipe.name}: ${generated.length} plants placed. Debug ${captured ? 'captured' : 'saved'}.`);
  };

  return createPortal(<section className="rounded-2xl border border-violet-500/50 bg-violet-950/25 p-3 text-slate-100">
    <div className="text-[10px] font-extrabold uppercase tracking-[.17em] text-violet-300">Plant recipe engine</div><div className="mt-1 text-sm font-bold">Recipe controls</div>
    <label className="mt-3 block text-xs text-slate-300">Recipe<select value={selectedId} onChange={event => setSelectedId(event.target.value)} className={inputClass}>{recipeCatalog.map(recipe => <option key={recipe.id} value={recipe.id}>{recipe.name}</option>)}</select></label>
    <div className="mt-3 grid grid-cols-2 gap-2"><label className="text-xs text-slate-300">Seed<input type="number" value={controls.seed} onChange={e => setControls(v => ({ ...v, seed: Number(e.target.value) || 1 }))} className={inputClass}/></label><div className="flex items-end"><button type="button" onClick={randomizeSeed} className={`${buttonClass} w-full`}>Random seed</button></div></div>
    <label className="mt-3 block text-xs text-slate-300">Fullness: {controls.density}%<input type="range" min="5" max="100" value={controls.density} onChange={e => setControls(v => ({ ...v, density: Number(e.target.value) }))} className="mt-1 w-full"/></label>
    <div className="mt-2 grid grid-cols-2 gap-2"><label className="text-xs text-slate-300">Target count<input type="number" min="1" placeholder="Auto" value={controls.targetCount ?? ''} onChange={e => setControls(v => ({ ...v, targetCount: e.target.value ? Number(e.target.value) : null }))} className={inputClass}/></label><label className="text-xs text-slate-300">Layout<select value={controls.layoutBehavior} onChange={e => setControls(v => ({ ...v, layoutBehavior: e.target.value as RecipeLayoutBehavior }))} className={inputClass}><option value="natural">Natural drift</option><option value="clumps">Tighter clumps</option><option value="even">Even spacing</option><option value="stacked">Stacked/orderly</option><option value="spread">Spread to fill</option></select></label></div>
    <div className="mt-3 space-y-2">{controls.plants.map(item => <div key={item.plantId} className="rounded-xl border border-slate-700/80 bg-slate-950/45 p-2"><div className="flex items-center gap-2"><input type="checkbox" checked={item.enabled} onChange={e => updatePlant(item.plantId, { enabled: e.target.checked })}/><div className="min-w-0 flex-1 truncate text-xs font-bold">{item.name}</div><span className="text-[10px] text-slate-400">#{item.plantId}</span></div><div className="mt-2 grid grid-cols-4 gap-1"><label className="text-[10px] text-slate-400">%<input type="number" value={item.weight} onChange={e => updatePlant(item.plantId, { weight: Number(e.target.value) })} className={inputClass}/></label><label className="text-[10px] text-slate-400">Count<input type="number" placeholder="Auto" value={item.count ?? ''} onChange={e => updatePlant(item.plantId, { count: e.target.value ? Number(e.target.value) : null })} className={inputClass}/></label><label className="text-[10px] text-slate-400">Width in<input type="number" value={item.widthInches} onChange={e => updatePlant(item.plantId, { widthInches: Number(e.target.value) })} className={inputClass}/></label><label className="text-[10px] text-slate-400">Clump<input type="number" step=".1" value={item.clump} onChange={e => updatePlant(item.plantId, { clump: Number(e.target.value) })} className={inputClass}/></label></div><label className="mt-1 block text-[10px] text-slate-400">Layer<select value={item.layer} onChange={e => updatePlant(item.plantId, { layer: e.target.value as RecipePhysicsLayer })} className={inputClass}><option value="front">Front</option><option value="middle">Middle</option><option value="back">Back</option><option value="accent">Accent</option></select></label></div>)}</div>
    <button type="button" onClick={() => setAdvancedOpen(v => !v)} className={`${buttonClass} mt-3 w-full`}>{advancedOpen ? 'Hide' : 'Show'} physics controls</button>
    {advancedOpen && <div className="mt-2 grid grid-cols-2 gap-2 rounded-xl border border-slate-700 bg-slate-950/35 p-2"><label className="text-xs text-slate-300">Allowed overlap %<input type="number" min="0" max="35" value={controls.allowedOverlap} onChange={e => setControls(v => ({ ...v, allowedOverlap: Number(e.target.value) }))} className={inputClass}/></label><label className="text-xs text-slate-300">Edge padding px<input type="number" min="0" value={controls.padding} onChange={e => setControls(v => ({ ...v, padding: Number(e.target.value) }))} className={inputClass}/></label><label className="text-xs text-slate-300">Settle iterations<input type="number" min="30" value={controls.iterations} onChange={e => setControls(v => ({ ...v, iterations: Number(e.target.value) }))} className={inputClass}/></label><label className="text-xs text-slate-300">Simulation passes<input type="number" min="1" max="8" value={controls.passes} onChange={e => setControls(v => ({ ...v, passes: Number(e.target.value) }))} className={inputClass}/></label><label className="text-xs text-slate-300">Layer attraction<input type="number" step=".1" min=".1" value={controls.attractionStrength} onChange={e => setControls(v => ({ ...v, attractionStrength: Number(e.target.value) }))} className={inputClass}/></label><label className="text-xs text-slate-300">Clump attraction<input type="number" step=".1" min="0" value={controls.clumpStrength} onChange={e => setControls(v => ({ ...v, clumpStrength: Number(e.target.value) }))} className={inputClass}/></label><label className="col-span-2 flex items-center gap-2 text-xs"><input type="checkbox" checked={controls.keepCentersInside} onChange={e => setControls(v => ({ ...v, keepCentersInside: e.target.checked }))}/>Keep plant centers inside zone</label><label className="col-span-2 flex items-center gap-2 text-xs"><input type="checkbox" checked={controls.replaceExisting} onChange={e => setControls(v => ({ ...v, replaceExisting: e.target.checked }))}/>Replace the current zone layout</label><div className="col-span-2 text-[10px] text-slate-400">Front edges: {currentZone?.edgeRoles?.front?.length || 0} · Back edges: {currentZone?.edgeRoles?.back?.length || 0}. Mark them with the zone edge controls above.</div></div>}
    <div className="mt-3 grid grid-cols-2 gap-2"><button type="button" onClick={() => generate(false)} className="rounded-xl bg-violet-600 px-3 py-2.5 text-sm font-bold hover:bg-violet-500">Generate</button><button type="button" onClick={() => generate(true)} className="rounded-xl bg-fuchsia-700 px-3 py-2.5 text-sm font-bold hover:bg-fuchsia-600">New seed + generate</button></div>
    <div className="mt-2 grid grid-cols-2 gap-2"><button type="button" onClick={() => selectedRecipe && setControls(defaultControls(selectedRecipe, currentZone))} className={buttonClass}>Restore defaults</button><input value={presetName} onChange={e => setPresetName(e.target.value)} placeholder="Preset name" className={inputClass}/><button type="button" onClick={savePreset} className={buttonClass}>Save preset</button><button type="button" onClick={loadPreset} className={buttonClass}>Load preset</button></div>
    {result && <div className="mt-3 grid grid-cols-4 gap-1 rounded-xl border border-violet-500/30 bg-slate-950/55 p-2 text-center"><div><b className="block text-sm">{result.placed}/{result.requested}</b><span className="text-[9px] text-slate-400">placed</span></div><div><b className="block text-sm">{result.rejected}</b><span className="text-[9px] text-slate-400">rejected</span></div><div><b className="block text-sm">{result.overlaps}</b><span className="text-[9px] text-slate-400">warnings</span></div><div><b className="block text-sm">{result.coverage}%</b><span className="text-[9px] text-slate-400">coverage</span></div><div><b className="block text-sm">{result.capacity}</b><span className="text-[9px] text-slate-400">capacity</span></div><div><b className="block text-sm">{result.passes}</b><span className="text-[9px] text-slate-400">passes</span></div><div className="col-span-2"><b className="block text-sm">{result.seed}</b><span className="text-[9px] text-slate-400">seed{result.capacityLimited ? ' · capped' : ''}</span></div></div>}
    {message && <div className="mt-2 rounded-lg border border-slate-700 bg-slate-900 px-2 py-2 text-xs text-slate-200">{message}</div>}
  </section>, host);
}

export default function RecipeAppIntegration() {
  const [host, setHost] = useState<HTMLElement | null>(null);
  useEffect(() => { let frame = 0; const findHost = () => { const plantingLabel = [...document.querySelectorAll('label')].find(label => label.textContent?.trim() === 'Planting type'); const plantingCard = plantingLabel?.closest('div.rounded-2xl'); const parent = plantingCard?.parentElement; if (!plantingCard || !parent) { setHost(null); return; } let recipeHost = parent.querySelector<HTMLElement>('[data-recipe-react-host]'); if (!recipeHost) { recipeHost = document.createElement('div'); recipeHost.dataset.recipeReactHost = 'true'; parent.insertBefore(recipeHost, plantingCard); } setHost(recipeHost); }; const observer = new MutationObserver(() => { cancelAnimationFrame(frame); frame = requestAnimationFrame(findHost); }); observer.observe(document.body, { childList: true, subtree: true }); findHost(); return () => { observer.disconnect(); cancelAnimationFrame(frame); }; }, []);
  return <><App />{host && <RecipePanel host={host} />}</>;
}
